const express=require('express');const axios=require('axios');
const app=express();const PORT=process.env.PORT||10000;
const API=(process.env.OSCAR_API||'https://admin.dramaramadan.net/api').replace(/\/$/,'');
const http=axios.create({timeout:10000,validateStatus:()=>true,headers:{'User-Agent':'OscarTV/1.1.5 (Android)','Accept':'application/json','X-App-Version':'1.1.5'}});
app.get('/manifest.json',(q,r)=>r.json({id:'community.oscartv.streams',version:'0.4.0',name:'OscarTV Streams',description:'OscarTV stream source',logo:'https://oscartv.app/favicon.ico',types:['movie','series'],idPrefixes:['tt'],resources:[{name:'stream',types:['movie','series'],idPrefixes:['tt']}]}));
const flat=o=>{let a=[];const walk=x=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}for(const [k,v] of Object.entries(x)){if(v!=null&&/^(streamUrl|stream_url|videoUrl|video_url|watchUrl|watch_url|url|src|link|file|m3u8|mp4|playUrl|play_url)$/i.test(k)){if(typeof v==='string')a.push(v);else walk(v)}else if(typeof v==='object')walk(v)}};walk(o);return [...new Set(a.filter(x=>/^https?:\/\//i.test(x)))]};
async function call(path,params,method='get'){let u=API+'/'+path;let r=method==='post'?await http.post(u,params):await http.get(u,{params});console.log('API',method,path,r.status,JSON.stringify(r.data).slice(0,700));return r}
async function probeMovie(imdb){const reqs=[
 ['movies/view.php',{imdb,imdbId:imdb,id:imdb}],['movies/show.php',{imdb,imdbId:imdb,id:imdb}],
 ['movies/',{searchQuery:imdb,filterSearch:imdb,search:imdb,query:imdb,page:1,per_page:50,limit:50}],
 ['movies/view.php',{external_id:imdb,externalId:imdb}],['movies/show.php',{external_id:imdb,externalId:imdb}]
 ];for(const [p,x] of reqs){for(const m of ['get','post']){try{const r=await call(p,x,m);const urls=flat(r.data);if(urls.length)return urls}catch(e){console.log('ERR',p,m,e.message)}}}return []}
async function probeEpisode(imdb,s,e){const seriesReq=[['series/view.php',{imdb,imdbId:imdb,id:imdb}],['series/show.php',{imdb,imdbId:imdb,id:imdb}],['series/',{searchQuery:imdb,filterSearch:imdb,search:imdb,query:imdb,page:1,per_page:50,limit:50}]];for(const [p,x] of seriesReq){for(const m of ['get','post']){try{const r=await call(p,x,m);const d=r.data;const urls=flat(d);if(urls.length)return urls;const ids=[];const walk=v=>{if(!v||typeof v!=='object')return;if(Array.isArray(v))return v.forEach(walk);for(const[k,z]of Object.entries(v)){if(/seasonId|season_id|episodeId|episode_id|id/i.test(k)&&typeof z==='number')ids.push(z);if(typeof z==='object')walk(z)}};walk(d);for(const id of ids.slice(0,10)){for(const ep of ['episodes/show.php','watch_links/']){for(const pm of [{id},{episode_id:id},{episodeId:id}]){try{const rr=await call(ep,pm,'get');const u=flat(rr.data);if(u.length)return u}catch{}}}}}catch(e){console.log('ERR',p,m,e.message)}}}return []}
app.get('/stream/:type/:id.json',async(req,res)=>{const raw=req.params.id.replace(/\.json$/,'');try{let urls=[];if(req.params.type==='movie'&&/^tt\d+$/.test(raw))urls=await probeMovie(raw);else if(req.params.type==='series'&&/^tt\d+:\d+:\d+$/.test(raw)){const [imdb,s,e]=raw.split(':');urls=await probeEpisode(imdb,+s,+e)}res.json({streams:urls.map((url,i)=>({name:'OscarTV',title:`OscarTV #${i+1}`,url}))})}catch(e){console.error(e);res.json({streams:[]})}});
app.get('/',(q,r)=>r.json({ok:true,api:API}));app.listen(PORT,()=>console.log(`OscarTV addon listening on ${PORT}; API=${API}`));
